global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: mysql
  metrics_path: /metrics
  honor_labels: false
  honor_timestamps: true
  sample_limit: 0
  scrape_interval: 15s
  scheme: http
  tls_config:
    insecure_skip_verify: true
  static_configs:
  - targets:
    - mysql_exporter:9104